services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logicalcobwebs
    restart: always
    volumes:
      - ./:/app:cached
    ports:
      - 8082:8082

volumes:
  logicalcobwebs-app:
